apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: exchange
  POSTGRES_USER: change_me
  POSTGRES_PASSWORD: change_me

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  API_KEY: api_key
  DATABASE_NAME: exchange
  DATABASE_USER: change_me
  DATABASE_PASSWORD: change_me
